9oormthon-univ/2024_BEOTKKOTTHON_TEAM_9_FE

lib/views/widget/adoption/Question.dart, lib/views/widget/adoption/Question2.dart, lib/views/widget/controller/responses_controller.dart, lib/views/widget/privacy/privacy_consent_screen.dart
-   close #15 
https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/ab54b494-8e93-4949-905d-9fa4e30b0972
=> ✨ feat : 규정 고지 스크린 생성

lib/bindings/root_binding.dart, lib/main.dart, lib/services/login_service.dart, lib/services/user_service.dart, lib/utilities/app_pages.dart, lib/utilities/app_routes.dart, lib/viewModels/login/login_viewmodel.dart, lib/views/home/home_screen.dart, lib/views/login/loading_screen.dart, lib/views/login/login_screen.dart, lib/views/root/root_screen.dart
-  [x] 첫화면 로그인 OR ROOT화면 나오도록 수정
-  [x] 첫화면 로그인 화면에서 홈화면으로 이동하도록 수정
=> ⚒️Fix: 로그인에서 홈화면으로 넘어가는 부분 수정

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/main.dart, lib/providers/AuthController.dart, lib/services/login_service.dart, lib/services/user_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/like/like_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/like/like_screen.dart, lib/views/login/loading_screen.dart, lib/views/login/login_screen.dart, lib/views/my/my_screen.dart, lib/views/root/root_screen.dart, pubspec.lock, pubspec.yaml
-  [x] 공고, 좋아요, 마이페이지 연동 준비
-  [x] 로그인 api 연동 수정 완료
=> ⚒️Fix: 로그인 api 연동 수정 및 다른 api(공고, 좋아요, 마이페이지) 연동 준비

lib/services/login_service.dart, lib/services/user_service.dart, lib/viewModels/like/like_viewmodel.dart
=> ✨feat : 메인화면, 좋아요 화면 api 연동

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/models/message/message_state.dart, lib/services/chat_service.dart, lib/services/login_service.dart, lib/services/user_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/home/home_viewmodel.dart, lib/viewModels/message/message_viewmodel.dart, pubspec.lock, pubspec.yaml
-   close #37 
-   [x] 채팅방 API
-   [x] 대화하기 스크린 API 연동
https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/f370b29b-7fa7-435d-aba7-7d87ca3d7a37
=> ✨ feat : 채팅방, 대화하기 스크린 API 연동 완료

lib/models/home/post_state.dart, lib/services/post_service.dart, lib/viewModels/home/post_viewmodel.dart, lib/views/home/post_screen.dart
=> ✨ feat : 공고 등록 API 연동 완료

ios/Podfile.lock, lib/main.dart, lib/models/my/my_state.dart, lib/services/chat_service.dart, lib/services/login_service.dart, lib/services/my_service.dart, lib/services/user_service.dart, lib/services/userpreferences_service.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/my/my_screen.dart, pubspec.lock, pubspec.yaml
=> ✨ feat: 로그인 유지 및 마이페이지 API 연동 세팅

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/models/privacy/privacy_state.dart, lib/services/privacy_service.dart, lib/services/userpreferences_service.dart, lib/utilities/font_system.dart, lib/viewModels/privacy/privacy_viewmodel.dart, lib/views/login/loading_screen.dart, lib/views/message/message_screen.dart, lib/views/widget/adoption/Question.dart, lib/views/widget/adoption/Question2.dart, lib/views/widget/privacy/hand_sign.dart, lib/views/widget/privacy/privacy_consent_screen.dart, pubspec.lock, pubspec.yaml
-   close #42 
https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/35ae8123-6bc3-45aa-970c-5bf9c2a4ec32
=> ✨ feat: 입양 신청 API 연동 완료

lib/main.dart, lib/models/home/dog_state.dart, lib/models/my/my_state.dart, lib/services/my_service.dart, lib/services/user_service.dart, lib/viewModels/home/doginfo_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/home/doginfo_screen.dart, lib/views/home/home_screen.dart, lib/views/like/like_screen.dart, lib/views/my/my_screen.dart
=> ✨feat : 홈화면 상세페이지 연동

lib/models/my/my_state.dart, lib/services/post_service.dart, lib/services/privacy_service.dart, lib/services/userpreferences_service.dart, lib/viewModels/home/post_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/home/home_screen.dart, lib/views/home/post_screen.dart, lib/views/my/my_screen.dart, lib/views/widget/adoption/Question2.dart
=> ✨ feat: 입양 신청/공고 페이지 service 수정, 마이페이지 api 연동 완료

lib/models/like/like_state.dart, lib/services/chat_service.dart, lib/services/like_service.dart, lib/services/user_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/like/like_viewmodel.dart, lib/viewModels/message/message_viewmodel.dart, lib/views/chat/chat_screen.dart, lib/views/home/home_screen.dart, lib/views/like/like_screen.dart, lib/views/widget/privacy/hand_sign.dart, pubspec.lock
-   close #45 
-   [x] 홈화면 상세페이지 API 연동
-   [x] 홈화면 좋아요 생성 삭제 API연동
-   [x] 좋아요 스크린 API 연동
-   [x] 좋아요 스크린 좋아요 생성 삭제 API 연동
=> ✨ feat: 홈화면 상세페이지 API, 좋아요 API 연동

lib/services/user_service.dart, lib/services/userpreferences_service.dart, lib/viewModels/message/message_viewmodel.dart, lib/views/chat/chat_screen.dart, lib/views/home/doginfo_screen.dart
-   close #52 
-   [x] 랜덤으로 대화하기 버튼 눌렀을 때 랜덤으로 PostId 설정하기
=> ✨ feat: 랜덤으로 대화하기 버튼 눌렀을 때 랜덤으로 PostId 설정하기

lib/services/login_service.dart, lib/services/user_service.dart, lib/views/home/home_screen.dart, lib/views/home/post_screen.dart, lib/views/root/root_screen.dart, lib/views/widget/adoption/Question.dart
=> ⚒️✨ fix, feat: 홈 화면 이름 연동으로 바꾸기, 입양 신청 딜레이 수정, 공고 스크린 메인이랑 잇기

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/Info.plist, lib/models/my/my_state.dart, lib/services/my_service.dart, lib/services/user_service.dart, lib/services/userpreferences_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/like/like_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/chat/chat_screen.dart, lib/views/home/home_screen.dart, lib/views/like/like_screen.dart, lib/views/my/my_screen.dart, lib/views/root/root_screen.dart
=> ⚒️ fix : 로그아웃, 좋아요 대화하기 마이페이지 리스트 없을때 화면 수정

android/app/build.gradle, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/services/post_service.dart, lib/services/user_service.dart, lib/services/userpreferences_service.dart, lib/utilities/font_system.dart, lib/views/home/home_screen.dart, lib/views/login/signin_screen.dart, pubspec.lock
=> ⚒️ fix : 회원가입 뷰 개선, 무한 스크롤 고치기

lib/viewModels/like/like_viewmodel.dart, lib/viewModels/message/message_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/home/doginfo_screen.dart, lib/views/like/like_screen.dart, lib/views/message/message_screen.dart
=> ⚒️ fix : 채팅 로그 나갔을 때 보이지 않도록 수정

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/services/privacy_service.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/like/like_screen.dart, lib/views/my/my_screen.dart
-   close #61 
-   [x] 입양 신청되면 마이페이지에 값 연동됨.
-   [x] 입양 신청 API 제대로 보내지는거 확인
=> ⚒️ fix: 입양 신청후 마이페이지 렌더링

lib/services/chat_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/message/message_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/views/home/home_screen.dart, lib/views/like/like_screen.dart, lib/views/message/message_screen.dart, lib/views/my/my_screen.dart, lib/views/widget/adoption/Question2.dart
-   [x] 입양 신청서 한 번 내면 제출 안되도록 로직 수정
=> ⚒️ fix: 입양 신청서 한 번 내면 제출 안되도록 로직 수정

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/viewModels/privacy/privacy_viewmodel.dart, lib/views/login/login_screen.dart, lib/views/message/message_screen.dart, lib/views/privacy/adoption_screen.dart, lib/views/widget/adoption/Question2.dart, pubspec.lock, pubspec.yaml
-   close #71 
-   [x] 입양신청서 스크린 리팩토링
-   [x] MVVM 초기 구축
스크린은 피그마에 맞게 수정했고, VM도 만들긴 했는데 나중에 api 명세서 보고 핏하게 맞춰야 합니다.
그리고 후에 입양 고지 스크린도 리팩토링 해서 두개 연결 맺어야 합니다.
https://github.com/user-attachments/assets/28a371b8-6236-495f-945c-74be14ecb491
=> ⚒️ fix: 입양신청서 스크린 리팩토링

lib/services/like_service.dart, lib/services/login_service.dart, lib/services/user_service.dart, lib/viewModels/home/home_viewmodel.dart, lib/viewModels/login/login_viewmodel.dart, lib/views/login/login_screen.dart
- 메인화면 제대로 연동되게 수정
- 좋아요 연동되게 수정
- 토큰 가져다 쓰는 로직 구현
=> ✨ feat: 메인화면 & 좋아요 토큰 추가

ios/Runner/Info.plist, pubspec.lock, pubspec.yaml
-   close #issue_number
-   [x]
=> fix: 주소 사이트 안열리는 문제 해결

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml, lib/bindings/root_binding.dart, lib/main_app.dart, lib/services/login_service.dart, lib/services/privacy_service.dart, lib/services/user_service.dart, lib/viewModels/chat/chat_viewmodel.dart, lib/viewModels/login/login_viewmodel.dart, lib/viewModels/my/my_viewmodel.dart, lib/viewModels/privacy/privacy_viewmodel.dart, lib/views/home/home_screen.dart, lib/views/my/my_screen.dart, lib/views/privacy/adoption_screen.dart, lib/views/privacy/regulatory_notice_screen.dart, lib/views/root/root_screen.dart, pubspec.yaml
=> feat: v1 업데이트
